version: '3'
services:
  broker:
    build: .
    image: humancellatlas/ingest-broker
    ports:
      - "5000:5000"
    environment:
      - INGEST_API=http://api.ingest.dev.data.humancellatlas.org
networks:
  default: